# global environment variables
environment:
  global:
    # path to source directory of project to be built
    PROJECT_DIR: .
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR_ARCH: x64

  # test matrix
  matrix:
    - TOOLCHAIN: "vs-16-2019-win64-cxx17"
      GENERATOR: Ninja

platform: x64

cache:
  - c:\tools\vcpkg\installed\
  - _build_%TOOLCHAIN%_Release\_deps\bgfx-build

before_build:
  # Required by -Gninja
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64

install:
  ############################################################################
  # Install Ninja
  ############################################################################
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - vcpkg install
            sdl2:%PLATFORM%-windows
            spdlog:%PLATFORM%-windows
            entt:%PLATFORM%-windows
            glm:%PLATFORM%-windows
            spirv-cross:%PLATFORM%-windows
            spirv-tools:%PLATFORM%-windows
            cxxopts:%PLATFORM%-windows
  - vcpkg list

build_script:
  # - cmd: cmake -H. -B_build_%TOOLCHAIN%_Debug -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%cd%\_install_%TOOLCHAIN%_DEBUG -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  # - cmd: cmake --build _build_%TOOLCHAIN%_Debug --config Debug
  - cmd: cmake -H. -B_build_%TOOLCHAIN%_Release -G "%GENERATOR%"
               -DOPENBLACK_BGFX_USE_SYSTEM_DEPS=ON
               -DCMAKE_INSTALL_PREFIX=%cd%\_install_%TOOLCHAIN%_RELEASE
               -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmd: cmake --build _build_%TOOLCHAIN%_Release --config Release
